dbpath = "Q:/DATA/SPRNL/Users/Shelley/databases/mona/raw/"

monarename = {
    'arrangement_number': 'arrnum',
    'country_name': 'country',
    'country_code': 'ifscode',
    'arrangement_type': 'facility',
    'approval_date': 'appdate',
    'approval_year': 'year',
    'initial_end_date': 'expdate',
    'revised_end_date': 'expdate_revise',
    'review_type': 'review_type',
    'review_sequence': 'review_seq',
    'totalaccess': 'amount',
    'precautionary': 'precautionary',
    'cancelled': 'cancel'
}

monameta = {
    'latest': '_20231218',
    '2023-12-18': '_20231218',
}

monatabdict = {
    'D': 'Description',
    'C': 'Combined',
    'M': 'Mecon',
    'P': 'Purchases',
    'Pro': 'Program',
    'Q': 'QPCandIndTarg',
    'QPC': 'QPC',
    'R': 'Reviews'
}

default = {
    'D' : [
        'arrangement_number',
        'country_name',
        'country_code',
        'arrangement_type',
        'approval_date',
        'approval_year',
        'initial_end_date',
        'revised_end_date',
        'review_type',
        'review_sequence',
        'totalaccess',
        'precautionary',
        'cancelled'],
    'C' : [
        'arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'revised_end_date',
         'board_action_date',
         'review_type',
         'review_status',
         'key_code',
         'economic_code',
         'economic_descriptor',
         'description',
         'description_code',
         'test_date',
         'pc_status',
         'comments',
         'sort',
         'esorder',
         'newtestdate',
         'added_at',
         'assessed_at',
         'unique_id',
         'parent_id'],
    'M':['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'intial_end_date',
         'initial_end_year',
         'revised_end_date',
         'duration_of_annual_arrangement_from',
         'duration_of_annual_arrangement_to',
         'board_action_date',
         'program_type',
         'review_type',
         'review_sequence',
         'mneumonic',
         'description',
         'program_year',
         'year_type',
         'fy_start_month',
         'fy_end_month',
         't_3',
         't_2',
         't_1',
         't',
         't_1',
         't_2',
         't_3',
         't_4',
         'indicator_currency',
         'sort'],
    'P': ['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'revised_end_date',
         'duration_of_annual_arrangement_from',
         'duration_of_annual_arrangement_to',
         'board_action_date',
         'program_type',
         'review_type',
         'review_sequence',
         'original_scheduled_date',
         'original_scheduled_amount',
         'original_basis',
         'original_scheduled_pc_date',
         'revised_scheduled_date',
         'revised_scheduled_amount',
         'revised_basis',
         'revised_scheduled_pc_date',
         'actual_date',
         'actual_amount',
         'actual_basis',
         'actual_set_aside',
         'actual_augmentation',
         'comments',
         'sort'],
    'Prog': ['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'revised_end_date',
         'duration_of_annual_arrangement_from',
         'duration_of_annual_arrangement_to',
         'board_action_date',
         'program_type',
         'review_type',
         'review_sequence',
         'board_document_number',
         'macroeconomic',
         'externalstability',
         'economicgrowth',
         'povertyreduction',
         'fiscalrevenue',
         'publicexpenditure',
         'monetary',
         'inflation',
         'exchangerate',
         'centralbank',
         'financialsector',
         'trade',
         'progrowth',
         'social',
         'enterprise',
         'governance',
         'other',
         'sort'],
    'IT': ['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'board_document_number',
         'program_type',
         'review_type',
         'review_sequence',
         'other',
         'criteria_description',
         'indicative_targets',
         'indicative_target_description',
         'test_date',
         'status',
         'program_amount',
         'revised_amount',
         'actual_amount',
         'adjusted_amount',
         'units',
         'comments',
         'is_it_test_date',
         'grouping'],
    'QPC': ['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'board_document_number',
         'program_type',
         'review_type',
         'review_sequence',
         'criteria_order',
         'main',
         'main_criteria_sequence',
         'sub',
         'sub_option',
         'dqpc_code',
         'test_date',
         'status',
         'program_amount',
         'revised_amount',
         'adjusted_amount',
         'actual_amount',
         'units',
         'comments',
         'is_it_test_date',
         'grouping'],
    'R': ['arrangement_number',
         'country_name',
         'country_code',
         'arrangement_type',
         'approval_date',
         'approval_year',
         'initial_end_date',
         'initial_end_year',
         'revised_end_date',
         'duration_of_annual_arrangement_from',
         'duration_of_annual_arrangement_to',
         'board_action_date',
         'program_type',
         'review_type',
         'review_sequence',
         'program_review_sequence',
         'program_review_frequency',
         'program_review_date',
         'program_review_revised_date',
         'program_review_revised_frequency',
         'program_review_completed_date',
         'program_review_comments',
         'financing_assurances_review_sequence',
         'financing_assurances_review_frequency',
         'financing_assurances_review_date',
         'financing_assurances_review_revised_date',
         'financing_assurances_review_revised_frequency',
         'financing_assurances_review_completed_date',
         'financing_assurances_review_comments',
         'sort']
}
